# Generated by Django 5.1.6 on 2025-02-28 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating_professors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moduleinstance',
            options={'verbose_name': 'Module Instance'},
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='created',
            new_name='created_at',
        ),
    ]
