# Generated by Django 5.1.6 on 2025-02-28 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_professors', '0002_alter_moduleinstance_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moduleinstance',
            options={},
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='score',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='student',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'module_instance', 'professor')},
        ),
        migrations.AddField(
            model_name='module',
            name='credits',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
