# Generated by Django 5.1.6 on 2025-03-06 07:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_professors', '0005_remove_rating_comment_alter_rating_module_instance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='credits',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='moduleinstance',
            name='year',
            field=models.PositiveIntegerField(help_text='Academic Year (e.g. 2018 for 2018-2019)', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
