# Generated by Django 5.1.6 on 2025-03-06 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_professors', '0006_alter_module_credits_alter_moduleinstance_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleinstance',
            name='students',
            field=models.ManyToManyField(related_name='module_instances', to=settings.AUTH_USER_MODEL),
        ),
    ]
