# Generated by Django 5.1.6 on 2025-03-11 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_professors', '0008_rating_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='rating_professors.professor'),
        ),
    ]
